Re-enable rfw tests
flutter/tests pull request #415
Opened 2024-10-11 21:24 UTC by victoreronmosele

This PR re-enables the `rfw` tests disabled in https://github.com/flutter/tests/pull/386. 

The `rfw` tests were fixed in https://github.com/flutter/packages/pull/7148.

Closes https://github.com/flutter/flutter/issues/151659.

2024-11-20 02:35 UTC, zanderso commented
I don't think this can land until the failing presubmits are addressed.

2024-11-20 11:45 UTC, victoreronmosele commented
Looking into the failing tests.

2024-12-03 12:59 UTC, victoreronmosele commented
Could the workflow be run please? To see if the failure is still happening.

2025-02-04 23:37 UTC, goderbauer commented
@victoreronmosele Could you resolve the merge conflicts? If you push a new commit that will also rerun all the tests. Thank you!

2025-02-05 00:23 UTC, victoreronmosele commented
@goderbauer I'll get on it.

2025-02-05 13:20 UTC, victoreronmosele commented
Hi @goderbauer, I'm seeing a "Merge is not an allowed merge method in this repository." message after pushing the commit. 

Do I still need to do anything else?

2025-02-05 17:18 UTC, goderbauer approved these changes
LGTM

2025-02-05 17:19 UTC, goderbauer commented
> Do I still need to do anything else?

No, I just need to find a secondary reviewer and then we should be able to land this.

2025-02-05 17:29 UTC, Piinks commented
LGTM! We'll need to update the pinned version in flutter/flutter after this lands

2025-02-05 17:29 UTC, Piinks approved these changes

2025-02-05 17:33 UTC, Piinks requested changes
Actually, sorry, double checking... shouldn't the commit here be updated to include the change from https://github.com/flutter/packages/pull/7148 that fixed this?

It looks like that change landed at
3890ceef72e140bc30cdeca59e0c70721f476fba
but this file checks out
0891835f8341b5c7bcd9d035a8d9c6b0f0039034

2025-02-05 21:52 UTC, victoreronmosele commented
@Piinks the change was made in the packages repo. Is there a way to include it here?

2025-02-05 22:01 UTC, Piinks commented
Yes, the file you are renaming specifies which commit from flutter/packages to checkout. :)

2025-02-05 22:09 UTC, victoreronmosele commented
Thanks! Will update the file.

2025-02-06 00:13 UTC, victoreronmosele commented
Updated the commit in the file.

2025-02-11 00:02 UTC, Piinks approved these changes
Perfect! Thank you! LGTM

2025-02-11 00:05 UTC, chunhtai approved these changes
LGTM

2025-02-11 00:19 UTC, zanderso commented
NB after this lands the flutter/tests commit needs to be manually rolled into flutter/flutter.

2025-02-11 00:23 UTC, merged

2025-02-11 01:05 UTC, victoreronmosele commented
Made a PR for the manual roll [here](https://github.com/flutter/flutter/pull/163030).